name: Lint

on:
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.3'  

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.57.2
          args: --timeout=2m
