name: Lint

on:
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.0' # Set Go version to 1.24

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6 # Use v6 of the action
        with:
          version: v1.64.2 # Use golangci-lint v1.64.2 or newer for Go 1.24 compatibility
          args: --timeout=2m
